### ISSUE TITLE
Typo in contact replacement?

### ISSUE THREAD

**Issue by Ace17** [JuliMuehl/tinyboxes#2]
https://github.com/JuliMuehl/tinyboxes/blob/main/src/TinyBoxes.cpp#L108

As I understand it, here we're trying to merge identical contacts.
The criteria to replace a contact currently is:

```
if((c.normal,contact.normal).NormSquared() <= CONTACT_TOLLERANCE && (c.point - contact.point).NormSquared() <= CONTACT_TOLLERANCE)
```

Shouldn't it read either: 

```
if((c.normal - contact.normal).NormSquared() <= CONTACT_TOLLERANCE && (c.point - contact.point).NormSquared() <= CONTACT_TOLLERANCE)
```
What do you think ?

**Comment by JuliMuehl** [comment]
Thank you for pointing that out. I fixed the typo and decided to go with a slightly different solution after revisiting the code.
```c++
float dot = Dot(c.normal,contact.normal);
if((1 - dot * dot) <= CONTACT_NORMAL_TOLLERANCE && (c.point - contact.point).NormSquared() <= CONTACT_POINT_TOLLERANCE && fabs(contact.depth - c.depth) <= CONTACT_DEPTH_TOLLERANCE )```
